// license:BSD-3-Clause
// copyright-holders:Nathan Woods
/***************************************************************************

    coco3.cpp

    TRS-80 Radio Shack Color Computer 3

  Functions to emulate general aspects of the machine (RAM, ROM, interrupts,
  I/O ports)

  The Dragon/CoCo2 have two PIAs.  These PIAs can trigger interrupts.  PIA0
  is set up to trigger IRQ on the CPU, and PIA1 can trigger FIRQ.  Each PIA
  has two output lines, and an interrupt will be triggered if either of these
  lines are asserted.

  -----  IRQ
  6809 |-<----------- PIA0
       |
       |
       |
       |
       | FIRQ
       |-<----------- PIA1
  -----

  The CoCo 3 still supports these interrupts, but the GIME can chose whether
  "old school" interrupts are generated, or the new ones generated by the GIME

  -----  IRQ
  6809 |-<----------- PIA0
       |       |                ------
       |       -<-------<-------|    |
       |                        |GIME|
       |       -<-------<-------|    |
       | FIRQ  |                ------
       |-<----------- PIA1
  -----

  In an email discussion with JK, he informs me that when GIME interrupts are
  enabled, this actually does not prevent PIA interrupts.  Apparently JeffV's
  CoCo 3 emulator did not handle this properly.

  It is worth noting that the CoCo 3 had two sets of VSync interrupts.
  To quote John Kowalski:

  One other thing to mention is that the old vertical interrupt and the new
  vertical interrupt are not the same..  The old one is triggered by the
  video's vertical sync pulse, but the new one is triggered on the next scan
  line *after* the last scan line of the active video display.  That is : new
  vertical interrupt triggers somewheres around scan line 230 of the 262 line
  screen (if a 200 line graphics mode is used, a bit earlier if a 192 line
  mode is used and a bit later if a 225 line mode is used).  The old vsync
  interrupt triggers on scanline zero.

  230 is just an estimate [(262-200)/2+200].  I don't think the active part
  of the screen is exactly centered within the 262 line total.  I can
  research that for you if you want an exact number for scanlines before the
  screen starts and the scanline that the v-interrupt triggers..etc.

***************************************************************************/

#include "emu.h"
#include "coco3.h"

//-------------------------------------------------
//  machine_start
//-------------------------------------------------

void coco3_state::machine_start()
{
	coco_state::machine_start();

	// save state support
	save_item(NAME(m_prev_keyboard_pressed));
	save_item(NAME(m_pia1b_control_register));

	// right joystick
	m_joy_handlers[0] = std::make_unique<coco_joy_standard>(*this, 0, ioport(JOYSTICK_BUTTONS_TAG));
	// left joystick
    m_joy_handlers[1] = std::make_unique<coco_joy_standard>(*this, 2, ioport(JOYSTICK_BUTTONS_TAG));
}



//-------------------------------------------------
//  ff20_write
//-------------------------------------------------

void coco3_state::ff20_write(offs_t offset, uint8_t data)
{
	coco_state::ff20_write(offset, data);

	/* The GIME monitors writes to the PIA to simulate a VDG */
	m_gime->pia_write(offset, data);
}



//-------------------------------------------------
//  ff40_read
//-------------------------------------------------

uint8_t coco3_state::ff40_read(offs_t offset)
{
	uint8_t result = 0x00;
	if (m_gime->spare_chip_select_enabled())
		result = coco_state::ff40_read(offset);
	return result;
}



//-------------------------------------------------
//  ff40_write
//-------------------------------------------------

void coco3_state::ff40_write(offs_t offset, uint8_t data)
{
	if (m_gime->spare_chip_select_enabled())
		coco_state::ff40_write(offset, data);
}



//-------------------------------------------------
//  on_keyboard_state_changed
//-------------------------------------------------

void coco3_state::on_keyboard_state_changed(bool any_pressed)
{
    if (any_pressed != m_prev_keyboard_pressed)
    {
        m_gime->set_il1(true);
        m_gime->set_il1(false);
        m_prev_keyboard_pressed = any_pressed;
    }
}



//-------------------------------------------------
//  cart_w
//-------------------------------------------------

void coco3_state::cart_w(bool state)
{
	coco_state::cart_w(state);
	m_gime->set_il0(state);
}



//-------------------------------------------------
//  update_cart_base
//-------------------------------------------------

void coco3_state::update_cart_base(uint8_t *cart_base)
{
	m_gime->update_cart_rom();
}



//-------------------------------------------------
//  screen_update
//-------------------------------------------------

uint32_t coco3_state::screen_update(screen_device &screen, bitmap_rgb32 &bitmap, const rectangle &cliprect)
{
	return (m_screen_config->read() & 1) ? m_gime->update_rgb(bitmap, cliprect) : m_gime->update_composite(bitmap, cliprect);
}
