// license:BSD-3-Clause
// copyright-holders:Nathan Woods
/***************************************************************************

    coco3.cpp

    TRS-80 Radio Shack Color Computer 3

  Functions to emulate general aspects of the machine (RAM, ROM, interrupts,
  I/O ports)

  The Dragon/CoCo2 have two PIAs.  These PIAs can trigger interrupts.  PIA0
  is set up to trigger IRQ on the CPU, and PIA1 can trigger FIRQ.  Each PIA
  has two output lines, and an interrupt will be triggered if either of these
  lines are asserted.

  -----  IRQ
  6809 |-<----------- PIA0
       |
       |
       |
       |
       |
       |-<----------- PIA1
  -----

  The CoCo 3 still supports these interrupts, but the GIME can chose whether
  "old school" interrupts are generated, or the new ones generated by the GIME

  -----  IRQ
  6809 |-<----------- PIA0
       |       |                ------
       |       -<-------<-------|    |
       |                        |GIME|
       |       -<-------<-------|    |
       | FIRQ  |                ------
       |-<----------- PIA1
  -----

  In an email discussion with JK, he informs me that when GIME interrupts are
  enabled, this actually does not prevent PIA interrupts.  Apparently JeffV's
  CoCo 3 emulator did not handle this properly.

***************************************************************************/

#include "emu.h"
#include "coco3.h"

//-------------------------------------------------
//  machine_start
//-------------------------------------------------

void coco3_state::machine_start()
{
	coco_state::machine_start();

	// save state support
	save_item(NAME(m_prev_keyboard_pressed));
	save_item(NAME(m_pia1b_control_register));

	m_joy_handlers[0] = std::make_unique<coco_joy_standard>(*this, 0); // Left
    m_joy_handlers[1] = std::make_unique<coco_joy_standard>(*this, 2); // Right
}



//-------------------------------------------------
//  ff20_write
//-------------------------------------------------

void coco3_state::ff20_write(offs_t offset, uint8_t data)
{
	coco_state::ff20_write(offset, data);

	/* The GIME monitors writes to the PIA to simulate a VDG */
	m_gime->pia_write(offset, data);
}



//-------------------------------------------------
//  ff40_read
//-------------------------------------------------

uint8_t coco3_state::ff40_read(offs_t offset)
{
	uint8_t result = 0x00;
	if (m_gime->spare_chip_select_enabled())
		result = coco_state::ff40_read(offset);
	return result;
}



//-------------------------------------------------
//  ff40_write
//-------------------------------------------------

void coco3_state::ff40_write(offs_t offset, uint8_t data)
{
	if (m_gime->spare_chip_select_enabled())
		coco_state::ff40_write(offset, data);
}



void coco3_state::pia0_pa_w(uint8_t value)
{
    // 1. Gather joystick buttons
//     uint8_t raw_buttons = ioport(JOYSTICK_BUTTONS_TAG)->read();
//     uint8_t gated_buttons = 0;
//     if (m_right_joy_device != 0) gated_buttons |= (raw_buttons & 0x05);
//     if (m_left_joy_device != 0)  gated_buttons |= (raw_buttons & 0x0a);
	uint8_t gated_buttons = m_joy_handlers[0]->button_status() | m_joy_handlers[1]->button_status();

    // Compute active-low driven rows (including joystick interference)
    uint8_t effective_value = value & ~gated_buttons;

    uint8_t pia0_pb = 0xFF;
    uint8_t any_pressed = 0;

    // 2. Single-pass keyboard matrix scan
    for (unsigned i = 0; i < m_keyboard.size(); i++)
    {
        uint8_t key_column = m_keyboard[i]->read();

        // Accumulate inverse bits for CoCo 3 interrupt logic (0 = pressed, so ~key_column finds pressed keys)
        any_pressed |= ~key_column;

        // Base CoCo behavior: update column state if this row is driven low (0)
        if (!(effective_value & (0x01 << i)))
        {
            pia0_pb &= key_column;
        }
    }

    // Include gated joystick buttons in the CoCo 3 interrupt check
    any_pressed |= gated_buttons;

    // 3. Update Peripheral Interface Adapter (PIA)
	pia_0().portb_w(pia0_pb);
//     pia_0().set_b_input(pia0_pb);

    // 4. CoCo 3 GIME Interrupt logic
    bool pressed = (any_pressed != 0);
    if (pressed != m_prev_keyboard_pressed)
    {
        m_gime->set_il1(true);
        m_gime->set_il1(false);
    }
    m_prev_keyboard_pressed = pressed;

// 	// Color Max 3 Trigger
// 	if ((m_right_joy_device == JOY_DEVICE_CM3_HIRES) && (value & 0x04))
// 		m_joy_handlers[0]->opamp_charge(m_mux->current_address(), int joy_val);
//
// 	if ((m_left_joy_device == JOY_DEVICE_CM3_HIRES) && (value & 0x08))
// 		m_joy_handlers[1].opamp_charge(m_mux->current_address(), int joy_val);
}

void coco3_state::pia0_pb_w(uint8_t value)
{
    // 1. Gather joystick buttons
//     uint8_t raw_buttons = ioport(JOYSTICK_BUTTONS_TAG)->read();
//     uint8_t gated_buttons = 0;
//     if (m_right_joy_device != 0) gated_buttons |= (raw_buttons & 0x05);
//     if (m_left_joy_device != 0)  gated_buttons |= (raw_buttons & 0x0a);
	uint8_t gated_buttons = m_joy_handlers[0]->button_status() | m_joy_handlers[1]->button_status();

    uint8_t pia0_pa = 0x7F;
    uint8_t any_pressed = 0;

    // 2. Single-pass keyboard matrix scan
    for (unsigned i = 0; i < m_keyboard.size(); i++)
    {
        uint8_t key_column = m_keyboard[i]->read();

        // Accumulate inverse bits for CoCo 3 GIME interrupt logic (0 = pressed)
        any_pressed |= ~key_column;

        // Base CoCo behavior: check if any columns driven low align with low bits in 'value'
        if ((key_column | value) != 0xFF)
        {
            pia0_pa &= ~(0x01 << i);
        }
    }

    // Apply base CoCo joystick interference
    pia0_pa &= ~gated_buttons;

    // Include gated joystick buttons in the CoCo 3 interrupt check
    any_pressed |= gated_buttons;

    // 3. Update Peripheral Interface Adapter (PIA)
	m_pia0_pa_buffer = (m_pia0_pa_buffer & ~0x7f) | (pia0_pa & 0x7f);
	pia_0().set_a_input(m_pia0_pa_buffer);

//     pia_0().set_a_input(pia0_pa, 0x7f);

    // 4. CoCo 3 GIME Interrupt logic
    bool pressed = (any_pressed != 0);
    if (pressed != m_prev_keyboard_pressed)
    {
        m_gime->set_il1(true);
        m_gime->set_il1(false);
    }
    m_prev_keyboard_pressed = pressed;
}

//-------------------------------------------------
//  keyboard_changed
//-------------------------------------------------

// INPUT_CHANGED_MEMBER(coco3_state::keyboard_changed)
// {
// // 	coco_state::keyboard_changed(field, param, oldval, newval);
//
// 	/* Support for CoCo 3 keyboard GIME interrupt */
// 	uint8_t any_pressed = 0;
// 	for (unsigned i = 0; i < m_keyboard.size(); i++)
// 	{
// 		any_pressed |= (~(m_keyboard[i]->read()) | poll_joystick_buttons()) & 0xff;
// 	}
//
// 	bool pressed = any_pressed != 0;
// 	if (pressed != m_prev_keyboard_pressed)
// 	{
// 		m_gime->set_il1(true);
// 		m_gime->set_il1(false);
// 	}
//
// 	m_prev_keyboard_pressed = pressed;
// }

//-------------------------------------------------
//  cart_w
//-------------------------------------------------

void coco3_state::cart_w(bool state)
{
	coco_state::cart_w(state);
	m_gime->set_il0(state);
}



//-------------------------------------------------
//  update_cart_base
//-------------------------------------------------

void coco3_state::update_cart_base(uint8_t *cart_base)
{
	m_gime->update_cart_rom();
}



//-------------------------------------------------
//  screen_update
//-------------------------------------------------

uint32_t coco3_state::screen_update(screen_device &screen, bitmap_rgb32 &bitmap, const rectangle &cliprect)
{
	return (m_screen_config->read() & 1) ? m_gime->update_rgb(bitmap, cliprect) : m_gime->update_composite(bitmap, cliprect);
}
